services:
  iut_service:
    container_name: iut_service
    image: node:lts
    working_dir: /usr/src/app
    env_file: ./service/.env
    volumes: 
      - ./service/api:/usr/src/app
    ports: 
      - 3333:3000
    command: npm start

networks:
  iut:
    driver: bridge