services:
  iut_api_priseDeCommande:
    container_name: iut_api_priseDeCommande
    image: node:lts
    env_file: ./service/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/api:/usr/src/app
    ports:
      - 8321:8321
    command: npm run dev
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut

  iut_api_suiviFabrication:
    container_name: iut_api_suiviFabrication
    image: node:lts
    env_file: ./service/.env
    working_dir: /usr/src/app
    volumes:
      - ./service/api:/usr/src/app
    ports:
      - 8322:8322
    command: npm run dev
    depends_on:
      - iut_db
    links:
      - iut_db
    networks:
      - iut

  iut_adminer:
    container_name: iut_adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - iut_db
    networks:
      - iut

  cache:
    container_name: cache
    image: redis:6
    networks:
      - iut

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - iut
    depends_on:
      - cache
      - iut_db
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'mysql'
      DB_HOST: 'localhost'
      DB_PORT: '3306'
      DB_DATABASE: 'serviceWeb'
      DB_USER: 'root'
      DB_PASSWORD: 'root'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'jfrancois5200@gmail.com'
      ADMIN_PASSWORD: 'd1rectuS'
      

  iut_db:
    container_name: iut_db
    image: mariadb:latest
    env_file: ./service/.env
    volumes:
      - ./service/db:/var/lib/mysql
      - ./service/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./service/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - iut

networks:
  iut:
    driver: bridge